// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: MPL-2.0

//! Generates JDK-independent canonical lowercase checks from the native Unicode tables.

use std::{fmt::Write, fs, path::Path};

fn main() {
    let mut boundaries = Vec::new();
    let mut inside = false;
    for point in 0..=0x110000 {
        let changes =
            char::from_u32(point).is_some_and(|ch| !ch.to_lowercase().eq(std::iter::once(ch)));
        if changes != inside {
            boundaries.push(point);
            inside = changes;
        }
    }
    let version = char::UNICODE_VERSION;
    let mut source = format!(
        "// Copyright (c) 2026 Glavo\n// SPDX-License-Identifier: MPL-2.0\n\n\
         package org.janex.reader.internal;\n\n\
         import java.util.Arrays;\n\n\
         /// Checks canonical lowercase spelling using Unicode {}.{}.{} independently of the JDK.\n\
         ///\n\
         /// @implNote Generated by `cargo run -p janex-format --example generate_java_case_checks`.\n\
         public final class UnicodeCaseChecks {{\n\
         \x20   /// Alternating inclusive starts and exclusive ends of code points changed by lowercasing.\n\
         \x20   private static final int[] CHANGES = {{\n",
        version.0, version.1, version.2
    );
    for chunk in boundaries.chunks(8) {
        source.push_str("        ");
        for point in chunk {
            write!(source, "0x{point:X}, ").unwrap();
        }
        source.truncate(source.trim_end().len());
        source.push('\n');
    }
    source.push_str(
        r#"    };

    /// Prevents instantiation.
    private UnicodeCaseChecks() {
    }

    /// Returns whether lowercasing leaves every code point in the nonnull string unchanged.
    public static boolean isLowercase(String value) {
        for (int offset = 0; offset < value.length();) {
            int point = value.codePointAt(offset);
            int index = Arrays.binarySearch(CHANGES, point);
            if (index >= 0 ? (index & 1) == 0 : (~index & 1) != 0) {
                return false;
            }
            offset += Character.charCount(point);
        }
        return true;
    }
}
"#,
    );
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    fs::write(
        root.join("janex-reader/src/main/java/org/janex/reader/internal/UnicodeCaseChecks.java"),
        source,
    )
    .unwrap();
}
