# Copyright (c) 2025 Glavo
# SPDX-License-Identifier: MPL-2.0

[package]
name = "janex-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "janex"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
janex-host.workspace = true
janex-java.workspace = true
janex-format.workspace = true
rpassword = "7"
zeroize = "1"
serde_json = "1"
serde = "1"

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
mimalloc.workspace = true

[dev-dependencies]
janex-signature.workspace = true
pgp = { version = "0.20", default-features = false }
tempfile = "3"

[lints]
workspace = true
