# Copyright (c) 2025 Glavo
# SPDX-License-Identifier: MPL-2.0

[workspace]
resolver = "3"
members = ["janex-format", "janex-signature", "janex-platform", "janex-java", "janex-host", "janex-cli", "janex-launcher"]

[workspace.package]
version = "0.1.0"
authors = ["Glavo"]
edition = "2024"

[workspace.dependencies]
janex-platform = { path = "janex-platform" }
janex-signature = { path = "janex-signature" }
janex-java = { path = "janex-java" }
janex-format = { path = "janex-format" }
janex-host = { path = "janex-host" }
mimalloc = { version = "0.1.52", features = ["override"] }
zstd = { version = "0.14", default-features = false, features = ["arrays", "zdict_builder"] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
