# Copyright (c) 2026 Glavo
# SPDX-License-Identifier: MPL-2.0

[package]
name = "janex-signature"
version.workspace = true
edition.workspace = true
license = "MPL-2.0"
description = "Detached signatures and explicit certificate authentication for Janex"

[dependencies]
cms = "0.2.3"
der = { version = "0.7", features = ["derive", "oid", "pem", "std"] }
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
p384 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
pgp = { version = "0.20", default-features = false }
pkcs8 = { version = "0.10", features = ["encryption", "pem", "std"] }
rand = "0.8"
rsa = { version = "0.9", features = ["sha2"] }
sha2-legacy = { package = "sha2", version = "0.10", features = ["oid"] }
signature = "2"
x509-cert = { version = "0.2", features = ["pem", "std"] }
zeroize = "1"

[lints]
workspace = true
