# Copyright (c) 2026 Glavo
# SPDX-License-Identifier: MPL-2.0

[versions]
aircompressor = "2.0.3"
bouncycastle = "1.86"

[libraries]
aircompressor = { module = "io.airlift:aircompressor", version.ref = "aircompressor" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-pgp = { module = "org.bouncycastle:bcpg-jdk18on", version.ref = "bouncycastle" }
