#!/usr/bin/env python3
"""Verify CMS signatures generated by the Janex CLI using an independent OpenSSL process."""

import argparse
import os
import pathlib
import shutil
import struct
import subprocess
import tempfile


def vuint(data, offset):
    """Read one ULEB128 value from a generated fixture's metadata."""
    value = 0
    for shift in range(0, 70, 7):
        byte = data[offset]
        offset += 1
        value |= (byte & 127) << shift
        if byte < 128:
            return value, offset
    raise ValueError("invalid ULEB128")


def main():
    """Pack four local fixtures, extract their signed metadata bytes, and verify them with OpenSSL."""
    root = pathlib.Path(__file__).resolve().parent
    project = root.parents[3]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--janex", default=str(project / "target/debug" / ("janex.exe" if os.name == "nt" else "janex")))
    fallback = pathlib.Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Git/usr/bin/openssl.exe"
    parser.add_argument("--openssl", default=shutil.which("openssl") or str(fallback))
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="janex-cms-interop-") as scratch:
        scratch = pathlib.Path(scratch)
        source = scratch / "source"
        source.mkdir()
        for name, algorithm in [("rsa256", "rsa-sha256"), ("rsa512", "rsa-sha512"), ("p256", "ecdsa-p256-sha256"), ("p384", "ecdsa-p384-sha384")]:
            package = scratch / f"{name}.janex"
            subprocess.run([args.janex, "pack", str(source), "--output", str(package), "--main-class", "Main",
                            "--cms-certificate", str(root / f"{name}.cert.pem"), "--cms-key", str(root / f"{name}.key.pem"),
                            "--cms-algorithm", algorithm], check=True, capture_output=True)
            data = package.read_bytes()
            assert data[-24:-16] == b"JANEXEND"
            metadata_length = struct.unpack_from("<Q", data, len(data) - 16)[0]
            start = len(data) - metadata_length
            size, offset = vuint(data, start + 16)
            offset += size
            assert data[offset] == 3
            document = data[start:offset + 1]
            size, offset = vuint(data, offset + 1)
            signature = data[offset:offset + size]
            signature_file, input_file, output_file = scratch / "signature.der", scratch / "input.bin", scratch / "output.bin"
            signature_file.write_bytes(signature)
            input_file.write_bytes(document)
            subprocess.run([args.openssl, "cms", "-verify", "-binary", "-inform", "DER", "-in", str(signature_file),
                            "-content", str(input_file), "-noverify", "-out", str(output_file)], check=True, capture_output=True)
            assert output_file.read_bytes() == document
            print(f"OpenSSL verified Janex {algorithm}")


if __name__ == "__main__":
    main()
