// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: MPL-2.0

//! Explicit operating-system integration with ownership-aware removal and configuration export.

mod render;

use crate::{Result, error::invalid};
use janex_format::checksum::{Algorithm, Checksum};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    io::{self, Write},
    path::{Path, PathBuf},
    process::Command,
};

/// Configuration for one registration or distribution export.
#[derive(Debug)]
pub struct Options {
    /// Absolute executable path embedded in generated handlers.
    pub executable: PathBuf,
    /// Trust arguments inserted before the file argument; paths must already be absolute.
    pub trust_arguments: Vec<String>,
    /// Selects machine-wide rather than current-user registration.
    pub system: bool,
    /// Also installs Linux direct execution support; requires machine-wide scope.
    pub binfmt: bool,
}

/// One string registry value owned by this installation.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
struct RegistryValue {
    /// Path relative to HKCU or HKLM.
    key: String,
    /// Value name; empty means the default value.
    name: String,
    /// Unexpanded REG_SZ contents.
    value: String,
}

/// One generated file before installation.
struct Asset {
    /// Absolute installed path.
    path: PathBuf,
    /// Relative distribution path inside an export directory.
    export: PathBuf,
    /// Complete generated contents.
    bytes: Vec<u8>,
    /// Unix executable permission.
    executable: bool,
}

/// Generated platform configuration ready for installation or export.
struct Plan {
    /// Files to install.
    assets: Vec<Asset>,
    /// Windows values to register.
    registry: Vec<RegistryValue>,
    /// MIME data directory whose cache should be refreshed.
    mime: Option<PathBuf>,
    /// Desktop-entry directory whose cache should be refreshed.
    desktop: Option<PathBuf>,
    /// macOS document-handler application directory.
    bundle: Option<PathBuf>,
}

/// Recorded contents of a generated file, used to preserve later external edits.
#[derive(Clone, Serialize, Deserialize)]
struct InstalledFile {
    /// Absolute installed path.
    path: PathBuf,
    /// SHA-256 of the generated bytes, used only for ownership comparison.
    digest: Vec<u8>,
}

/// One complete desired installation.
#[derive(Clone, Serialize, Deserialize)]
struct Manifest {
    /// Executable selected at registration time.
    executable: PathBuf,
    /// Generated files and their ownership fingerprints.
    files: Vec<InstalledFile>,
    /// Generated registry values.
    registry: Vec<RegistryValue>,
    /// Whether the installation includes a binfmt rule.
    binfmt: bool,
    /// MIME directory to refresh after changes.
    mime: Option<PathBuf>,
    /// Desktop directory to refresh after changes.
    desktop: Option<PathBuf>,
    /// Application bundle to register with Launch Services.
    bundle: Option<PathBuf>,
}

/// Previous and desired manifests retained until an update finishes successfully.
#[derive(Default, Serialize, Deserialize)]
struct Record {
    /// A successful registration has exactly one manifest; interrupted updates may have more.
    manifests: Vec<Manifest>,
}

/// Read-only registration status for one user or system scope.
#[derive(Debug, Serialize)]
pub struct Status {
    /// Whether any registration record exists.
    pub registered: bool,
    /// Whether all desired entries and the registered executable are present and unchanged.
    pub complete: bool,
    /// Whether the recorded binfmt rule is currently active.
    pub binfmt_active: bool,
    /// Absolute registered executable, if a record exists.
    pub executable: Option<PathBuf>,
    /// Missing or externally changed entries.
    pub problems: Vec<String>,
}

/// Resolves the persistent ownership record independently of exported assets.
fn record_path(system: bool) -> Result<PathBuf> {
    if !system {
        return Ok(janex_platform::janex_home()?.join("integration/registration.json"));
    }
    #[cfg(windows)]
    let root = env_path("ProgramData")?.join("Janex/integration");
    #[cfg(target_os = "macos")]
    let root = PathBuf::from("/Library/Application Support/Janex/integration");
    #[cfg(not(any(windows, target_os = "macos")))]
    let root = PathBuf::from("/var/lib/janex/integration");
    Ok(root.join("registration.json"))
}

/// Reads an absolute operating-system directory from the environment.
fn env_path(name: &str) -> Result<PathBuf> {
    let path = std::env::var_os(name)
        .map(PathBuf::from)
        .filter(|path| path.is_absolute())
        .ok_or_else(|| invalid(format!("{name} must name an absolute directory")))?;
    Ok(path)
}

/// Loads a record without creating directories.
fn load(path: &Path) -> Result<Record> {
    match fs::read(path) {
        Ok(bytes) => serde_json::from_slice(&bytes)
            .map_err(|error| invalid(format!("invalid integration record: {error}"))),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(Record::default()),
        Err(error) => Err(error.into()),
    }
}

/// Atomically replaces one generated file in its existing or newly created parent directory.
fn write(path: &Path, bytes: &[u8], executable: bool) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| invalid("integration file has no parent"))?;
    fs::create_dir_all(parent)?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(bytes)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(if executable {
                0o755
            } else {
                0o644
            }))?;
    }
    #[cfg(not(unix))]
    let _ = executable;
    temporary.persist(path).map_err(|error| error.error)?;
    Ok(())
}

/// Stores a recovery record before modifying registered entries.
fn save(path: &Path, record: &Record) -> Result<()> {
    write(
        path,
        &serde_json::to_vec_pretty(record).map_err(|error| invalid(error.to_string()))?,
        false,
    )
}

/// Computes an ownership fingerprint for generated configuration bytes.
fn digest(bytes: &[u8]) -> Result<Vec<u8>> {
    Ok(Checksum::compute(Algorithm::Sha256, bytes)?
        .digest()
        .to_vec())
}

/// Reads a regular generated file without following a replacement symbolic link.
fn existing(path: &Path) -> Result<Option<Vec<u8>>> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_file() => Ok(Some(digest(&fs::read(path)?)?)),
        Ok(_) => Err(invalid(format!(
            "integration path is not a regular file: {}",
            path.display()
        ))),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error.into()),
    }
}

/// Refuses to overwrite or remove entries whose contents are not in the recovery record.
fn preflight(record: &Record, system: bool) -> Result<()> {
    for manifest in &record.manifests {
        for file in &manifest.files {
            if let Some(value) = existing(&file.path)?
                && !record
                    .manifests
                    .iter()
                    .flat_map(|m| &m.files)
                    .any(|f| f.path == file.path && f.digest == value)
            {
                return Err(invalid(format!(
                    "integration file was changed externally: {}",
                    file.path.display()
                )));
            }
        }
        for entry in &manifest.registry {
            if let Some(value) = registry_get(system, entry)?
                && !record
                    .manifests
                    .iter()
                    .flat_map(|m| &m.registry)
                    .any(|e| e.key == entry.key && e.name == entry.name && e.value == value)
            {
                return Err(invalid(format!(
                    "integration registry value was changed externally: {}\\{}",
                    entry.key, entry.name
                )));
            }
        }
    }
    Ok(())
}

/// Serializes live updates within one registration scope.
fn lock(path: &Path) -> Result<fs::File> {
    fs::create_dir_all(path.parent().expect("record parent"))?;
    let file = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(path.with_extension("lock"))?;
    fs4::FileExt::lock(&file)?;
    Ok(file)
}

/// Installs or updates the selected scope and returns cache-refresh warnings.
///
/// Existing entries must match a recorded or requested value. Interrupted updates retain their
/// recovery record so register or unregister can be retried. No default application is selected.
pub fn register(options: &Options) -> Result<Vec<String>> {
    validate(options)?;
    let path = record_path(options.system)?;
    let _lock = lock(&path)?;
    let mut record = load(&path)?;
    let plan = render::plan(options)?;
    let desired = manifest(options, &plan)?;
    if record.manifests.iter().any(|m| m.binfmt) || options.binfmt {
        check_binfmt()?;
    }
    if options.binfmt && !Path::new("/proc/sys/fs/binfmt_misc/register").is_file() {
        return Err(invalid(
            "binfmt_misc is not mounted; mount it before registering --binfmt",
        ));
    }
    record.manifests.push(desired.clone());
    preflight(&record, options.system)?;
    save(&path, &record)?;
    for asset in &plan.assets {
        write(&asset.path, &asset.bytes, asset.executable)?;
    }
    for entry in &plan.registry {
        registry_set(options.system, entry)?;
    }
    if record.manifests.iter().any(|m| m.binfmt) {
        remove_binfmt()?;
    }
    if options.binfmt {
        fs::write("/proc/sys/fs/binfmt_misc/register", render::BINFMT_RULE)?;
    }
    let mut warnings = Vec::new();
    for previous in &record.manifests {
        if previous.bundle.is_some() && previous.bundle != desired.bundle {
            warnings.extend(refresh(previous, true));
        }
    }
    remove_obsolete(&record, Some(&desired), options.system)?;
    for previous in &record.manifests {
        if previous.bundle.is_none()
            && (previous.mime != desired.mime || previous.desktop != desired.desktop)
        {
            warnings.extend(refresh(previous, true));
        }
    }
    warnings.extend(refresh(&desired, false));
    record.manifests = vec![desired];
    save(&path, &record)?;
    Ok(warnings)
}

/// Removes unchanged managed entries and returns cache-refresh warnings; absence is a no-op.
/// Externally changed entries cause an error before any removal.
pub fn unregister(system: bool) -> Result<Vec<String>> {
    let path = record_path(system)?;
    if !path.exists() {
        return Ok(Vec::new());
    }
    let _lock = lock(&path)?;
    let record = load(&path)?;
    preflight(&record, system)?;
    if record.manifests.iter().any(|m| m.binfmt) {
        check_binfmt()?;
        remove_binfmt()?;
    }
    let mut warnings = Vec::new();
    for manifest in &record.manifests {
        if manifest.bundle.is_some() {
            warnings.extend(refresh(manifest, true));
        }
    }
    remove_obsolete(&record, None, system)?;
    for manifest in &record.manifests {
        if manifest.bundle.is_none() {
            warnings.extend(refresh(manifest, true));
        }
    }
    fs::remove_file(path)?;
    Ok(warnings)
}

/// Removes recorded entries absent from the new manifest, without recursive directory removal.
fn remove_obsolete(record: &Record, desired: Option<&Manifest>, system: bool) -> Result<()> {
    for old in &record.manifests {
        for file in &old.files {
            if desired.is_some_and(|m| m.files.iter().any(|f| f.path == file.path)) {
                continue;
            }
            match fs::remove_file(&file.path) {
                Ok(()) => (),
                Err(error) if error.kind() == io::ErrorKind::NotFound => (),
                Err(error) => return Err(error.into()),
            }
            if let Some(bundle) = &old.bundle {
                let mut parent = file.path.parent();
                while let Some(directory) = parent.filter(|p| p.starts_with(bundle)) {
                    let _ = fs::remove_dir(directory);
                    parent = directory.parent();
                }
            }
        }
        for entry in old.registry.iter().rev() {
            if !desired.is_some_and(|m| {
                m.registry
                    .iter()
                    .any(|e| e.key == entry.key && e.name == entry.name)
            }) {
                registry_remove(system, entry)?;
            }
        }
    }
    Ok(())
}

/// Reports recorded registration and live binfmt activation without making changes.
pub fn status(system: bool) -> Result<Status> {
    let record = load(&record_path(system)?)?;
    let mut result = Status {
        registered: !record.manifests.is_empty(),
        complete: false,
        binfmt_active: false,
        executable: None,
        problems: Vec::new(),
    };
    let Some(desired) = record.manifests.last() else {
        return Ok(result);
    };
    result.executable = Some(desired.executable.clone());
    if !desired.executable.is_file() {
        result
            .problems
            .push("registered executable is missing".into());
    }
    if record.manifests.len() != 1 {
        result
            .problems
            .push("registration update is incomplete".into());
    }
    for file in &desired.files {
        if !matches!(existing(&file.path), Ok(Some(value)) if value == file.digest) {
            result
                .problems
                .push(format!("missing or changed file: {}", file.path.display()));
        }
    }
    for entry in &desired.registry {
        if !matches!(registry_get(system, entry), Ok(Some(value)) if value == entry.value) {
            result.problems.push(format!(
                "missing or changed registry value: {}\\{}",
                entry.key, entry.name
            ));
        }
    }
    if desired.binfmt {
        result.binfmt_active = check_binfmt().is_ok()
            && fs::read_to_string("/proc/sys/fs/binfmt_misc/janex")
                .is_ok_and(|value| value.lines().next() == Some("enabled"))
            && fs::read_to_string("/proc/sys/fs/binfmt_misc/status")
                .is_ok_and(|value| value.trim() == "enabled");
        if !result.binfmt_active {
            result.problems.push("binfmt rule is not active".into());
        }
    }
    result.complete = result.problems.is_empty();
    Ok(result)
}

/// Exports native-platform assets into a new directory without changing live registration.
pub fn export(options: &Options, output: &Path) -> Result<()> {
    validate(options)?;
    let plan = render::plan(options)?;
    fs::create_dir(output)?;
    for asset in &plan.assets {
        write(&output.join(&asset.export), &asset.bytes, asset.executable)?;
    }
    if !plan.registry.is_empty() {
        write(
            &output.join("janex.reg"),
            &render::reg_file(options.system, &plan.registry),
            false,
        )?;
    }
    write(
        &output.join("README.txt"),
        render::instructions(options).as_bytes(),
        false,
    )
}

/// Checks platform scope and command arguments before generation or mutation.
fn validate(options: &Options) -> Result<()> {
    if !options.executable.is_absolute() {
        return Err(invalid("integration executable must be an absolute path"));
    }
    if options.binfmt && (!options.system || !cfg!(target_os = "linux")) {
        return Err(invalid("--binfmt requires --system on Linux"));
    }
    if cfg!(all(unix, not(target_os = "macos")))
        && options.executable.to_string_lossy().contains('=')
    {
        return Err(invalid("Desktop Entry executable paths cannot contain '='"));
    }
    for value in options
        .trust_arguments
        .iter()
        .map(String::as_str)
        .chain(Some(options.executable.to_str().ok_or_else(|| {
            invalid("integration executable path is not Unicode")
        })?))
    {
        if value.chars().any(char::is_control) {
            return Err(invalid("control character in integration command"));
        }
    }
    Ok(())
}

/// Converts rendered assets into ownership information without retaining duplicate file contents.
fn manifest(options: &Options, plan: &Plan) -> Result<Manifest> {
    Ok(Manifest {
        executable: options.executable.clone(),
        files: plan
            .assets
            .iter()
            .map(|asset| {
                Ok(InstalledFile {
                    path: asset.path.clone(),
                    digest: digest(&asset.bytes)?,
                })
            })
            .collect::<Result<_>>()?,
        registry: plan.registry.clone(),
        binfmt: options.binfmt,
        mime: plan.mime.clone(),
        desktop: plan.desktop.clone(),
        bundle: plan.bundle.clone(),
    })
}

/// Refreshes platform caches; missing utilities leave usable assets and produce warnings.
fn refresh(manifest: &Manifest, removing: bool) -> Vec<String> {
    let mut warnings = Vec::new();
    let mut commands = Vec::new();
    if let Some(path) = &manifest.mime {
        commands.push(("update-mime-database", vec![path.as_os_str()]));
    }
    if let Some(path) = &manifest.desktop {
        commands.push(("update-desktop-database", vec![path.as_os_str()]));
    }
    if let Some(path) = &manifest.bundle {
        commands.push(("/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister", vec![std::ffi::OsStr::new(if removing { "-u" } else { "-f" }), path.as_os_str()]));
    }
    for (program, args) in commands {
        match Command::new(program).args(args).output() {
            Ok(output) if output.status.success() => (),
            Ok(output) => warnings.push(format!(
                "{program}: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            )),
            Err(error) => warnings.push(format!("{program}: {error}")),
        }
    }
    #[cfg(windows)]
    janex_platform::registry::notify();
    warnings
}

/// Reads one platform registry value.
fn registry_get(system: bool, entry: &RegistryValue) -> Result<Option<String>> {
    #[cfg(windows)]
    {
        Ok(janex_platform::registry::get(
            system,
            &entry.key,
            &entry.name,
        )?)
    }
    #[cfg(not(windows))]
    {
        let _ = (system, entry);
        Err(crate::Error::Unsupported(
            "Windows registry is unavailable".into(),
        ))
    }
}

/// Writes one platform registry value.
fn registry_set(system: bool, entry: &RegistryValue) -> Result<()> {
    #[cfg(windows)]
    {
        Ok(janex_platform::registry::set(
            system,
            &entry.key,
            &entry.name,
            &entry.value,
        )?)
    }
    #[cfg(not(windows))]
    {
        let _ = (system, entry);
        Err(crate::Error::Unsupported(
            "Windows registry is unavailable".into(),
        ))
    }
}

/// Removes one platform registry value.
fn registry_remove(system: bool, entry: &RegistryValue) -> Result<()> {
    #[cfg(windows)]
    {
        Ok(janex_platform::registry::remove(
            system,
            &entry.key,
            &entry.name,
        )?)
    }
    #[cfg(not(windows))]
    {
        let _ = (system, entry);
        Err(crate::Error::Unsupported(
            "Windows registry is unavailable".into(),
        ))
    }
}

/// Rejects a same-named binfmt registration belonging to another interpreter.
fn check_binfmt() -> Result<()> {
    match fs::read_to_string("/proc/sys/fs/binfmt_misc/janex") {
        Ok(value)
            if value
                .lines()
                .any(|s| s == "interpreter /usr/libexec/janex-binfmt")
                && value.lines().any(|s| s == "magic 4a414e4558000000")
                && value.lines().any(|s| s == "offset 0")
                && value.lines().any(|s| s.trim_end() == "flags:")
                && value
                    .lines()
                    .filter_map(|s| s.strip_prefix("mask "))
                    .all(|s| s == "ffffffffffffffff") =>
        {
            Ok(())
        }
        Ok(_) => Err(invalid(
            "binfmt registration 'janex' belongs to another configuration",
        )),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

/// Removes only the previously checked Janex binfmt entry.
fn remove_binfmt() -> Result<()> {
    if Path::new("/proc/sys/fs/binfmt_misc/janex").is_file() {
        fs::write("/proc/sys/fs/binfmt_misc/janex", b"-1")?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Records one generated configuration for isolated ownership tests.
    fn configuration(path: PathBuf, contents: &[u8]) -> Manifest {
        Manifest {
            executable: std::env::current_exe().unwrap(),
            files: vec![InstalledFile {
                path,
                digest: digest(contents).unwrap(),
            }],
            registry: Vec::new(),
            binfmt: false,
            mime: None,
            desktop: None,
            bundle: None,
        }
    }

    #[test]
    fn recovery_accepts_partial_updates_and_rejects_external_edits() {
        let temp = tempfile::tempdir().unwrap();
        let file = temp.path().join("managed");
        let record_path = temp.path().join("registration.json");
        let old = configuration(file.clone(), b"old");
        let desired = configuration(file.clone(), b"new");
        let record = Record {
            manifests: vec![old, desired.clone()],
        };
        save(&record_path, &record).unwrap();
        let record = load(&record_path).unwrap();
        for contents in [b"old", b"new"] {
            write(&file, contents, false).unwrap();
            preflight(&record, false).unwrap();
            remove_obsolete(&record, Some(&desired), false).unwrap();
            assert_eq!(fs::read(&file).unwrap(), contents);
        }
        fs::write(&file, b"foreign").unwrap();
        assert!(preflight(&record, false).is_err());
        assert_eq!(fs::read(&file).unwrap(), b"foreign");
        write(&file, b"new", false).unwrap();
        preflight(&record, false).unwrap();
        let unrelated = temp.path().join("unrelated");
        fs::write(&unrelated, b"keep").unwrap();
        remove_obsolete(&record, None, false).unwrap();
        assert!(!file.exists());
        assert_eq!(fs::read(unrelated).unwrap(), b"keep");
        preflight(&record, false).unwrap();
    }
}
