// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: MPL-2.0

//! Cross-language codec fixtures generated by libzstd and the Rust format implementation.

use janex_format::{binary::Limits, classfile, strings::StringPool};
use std::{
    fs,
    io::{Read, Write},
    path::Path,
    process::Command,
};

/// Executes a JDK tool and retains failure diagnostics.
fn tool(directory: &Path, executable: &str, args: &[&str]) {
    let output = Command::new(executable)
        .current_dir(directory)
        .args(args)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{executable}: {}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// Encodes a frame with an independent native Zstandard implementation.
fn frame(bytes: &[u8], level: i32) -> Vec<u8> {
    let mut encoder = zstd::stream::Encoder::new(Vec::new(), level).unwrap();
    encoder.include_checksum(level != 1).unwrap();
    if level > 1 {
        encoder
            .set_pledged_src_size(Some(bytes.len() as u64))
            .unwrap();
    }
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}

/// Appends a nonnegative fixture integer.
fn number(output: &mut Vec<u8>, size: usize) {
    output.extend_from_slice(&(size as u32).to_be_bytes());
}

/// Appends a codec vector with its independent expected bytes and selected pool.
fn vector(
    output: &mut Vec<u8>,
    kind: u8,
    valid: bool,
    input: &[u8],
    expected: &[u8],
    pool: &StringPool,
) {
    output.extend([kind, u8::from(valid)]);
    number(output, input.len());
    output.extend(input);
    number(output, expected.len());
    output.extend(expected);
    number(output, pool.len());
    for i in 0..pool.len() {
        let text = pool.get(i as u64).unwrap();
        number(output, text.encode_utf16().count());
        for unit in text.encode_utf16() {
            output.extend_from_slice(&unit.to_be_bytes());
        }
    }
}

#[test]
fn java_decoders_match_native_frames_and_exact_classfile_bytes() {
    let temp = tempfile::tempdir().unwrap();
    let project = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let jar = project.join("janex-bootstrap/build/libs/janex-bootstrap.jar");
    let harness = project
        .join("janex-reader/src/testFixtures/java/org/janex/reader/internal/codec/CodecTest.java");
    let boundary_harness = project.join(
        "janex-reader/src/testFixtures/java/org/janex/reader/internal/codec/ZstandardTest.java",
    );
    tool(
        temp.path(),
        "javac",
        &[
            "--release",
            "8",
            "-cp",
            jar.to_str().unwrap(),
            "-d",
            "classes",
            harness.to_str().unwrap(),
            boundary_harness.to_str().unwrap(),
        ],
    );
    let pool = StringPool::new();
    let mut vectors = vec![0; 4];
    let mut count = 0;
    for size in [0, 1, 16, 128, 1024, 65537, 131071, 131072, 131073, 1048576] {
        let mut state = 0x123456789abcdef0u64;
        let bytes: Vec<_> = (0..size)
            .map(|index| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                if index % 29 < 17 {
                    (index % 251) as u8
                } else {
                    state as u8
                }
            })
            .collect();
        for level in [-3, 1, 3, 9, 19] {
            vector(&mut vectors, 0, true, &frame(&bytes, level), &bytes, &pool);
            count += 1;
        }
    }
    // Vary symbol distributions and repetition distances across independent compressor levels.
    let mut state = 0x9e3779b97f4a7c15u64;
    for case in 0..120 {
        let size = 257 + case * 2003;
        let alphabet = [2, 3, 7, 16, 65, 129, 256][case % 7];
        let mut bytes = Vec::with_capacity(size);
        for index in 0..size {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            let distance = [1, 4, 8, 31, 256, 4093, 32768][case % 7];
            let byte = if index >= distance && (state & 7) < 5 {
                bytes[index - distance]
            } else {
                ((state >> 16) % alphabet) as u8
            };
            bytes.push(byte);
        }
        let level = [-5, 1, 2, 5, 12, 19, 22][case % 7];
        vector(&mut vectors, 0, true, &frame(&bytes, level), &bytes, &pool);
        count += 1;
    }
    // Native decoding supplies the expected result even when a mutation remains valid.
    let mutation_plain: Vec<_> = (0..8192).map(|i| ((i * 7 + i / 29) % 113) as u8).collect();
    for level in [1, 3] {
        let encoded = frame(&mutation_plain, level);
        for case in 0..256 {
            let mut mutated = encoded.clone();
            let position = 10 + case * 131 % (mutated.len() - 10);
            mutated[position] ^= 1 << (case % 8);
            let mut native = Vec::new();
            let valid = zstd::stream::Decoder::new(mutated.as_slice())
                .and_then(|decoder| decoder.take(1048577).read_to_end(&mut native))
                .is_ok()
                && native.len() <= 1048576;
            let expected = if valid {
                native
            } else {
                vec![0; mutation_plain.len()]
            };
            vector(&mut vectors, 0, valid, &mutated, &expected, &pool);
            count += 1;
        }
    }
    let first = vec![b'x'; 20000];
    let second = vec![b'y'; 20000];
    let mut frames = frame(&first, 3);
    frames.extend_from_slice(&[0x50, 0x2a, 0x4d, 0x18, 3, 0, 0, 0, 1, 2, 3]);
    frames.extend(frame(&[], 3));
    frames.extend(frame(&second, 9));
    vector(
        &mut vectors,
        0,
        true,
        &frames,
        &[first, second].concat(),
        &pool,
    );
    count += 1;
    let plain = vec![b'z'; 10000];
    let compressed = frame(&plain, 3);
    for end in 0..compressed.len() {
        vector(&mut vectors, 0, false, &compressed[..end], &plain, &pool);
        count += 1;
    }
    let mut checksum = compressed.clone();
    *checksum.last_mut().unwrap() ^= 1;
    vector(&mut vectors, 0, false, &checksum, &plain, &pool);
    count += 1;
    let mut reserved = compressed.clone();
    reserved[4] |= 8;
    vector(&mut vectors, 0, false, &reserved, &plain, &pool);
    count += 1;
    let mut trailing = compressed.clone();
    trailing.push(0);
    vector(&mut vectors, 0, false, &trailing, &plain, &pool);
    count += 1;
    vector(
        &mut vectors,
        0,
        false,
        &compressed,
        &plain[..plain.len() - 1],
        &pool,
    );
    count += 1;
    vector(&mut vectors, 0, false, &[], &[], &pool);
    count += 1;
    vector(
        &mut vectors,
        0,
        false,
        &[
            0x28, 0xb5, 0x2f, 0xfd, 0xc0, 0, 0, 0, 0, 0, 0, 0, 0, 0x80, 1, 0, 0,
        ],
        &[],
        &pool,
    );
    count += 1;
    vector(
        &mut vectors,
        0,
        false,
        &[0x50, 0x2a, 0x4d, 0x18, 0, 0, 0, 0],
        &[],
        &pool,
    );
    count += 1;
    fs::write(
        temp.path().join("Fixture.java"),
        r#"
public class Fixture {
    static final String TEXT = "A sufficiently long shared string with \u0000 and \ud83d\ude80";
    static final long LONG = 0x123456789abcdef0L;
    static final double DOUBLE = 1.25;
    java.util.List<String> values = new java.util.ArrayList<String>();
    public static void main(String[] args) { System.out.println(TEXT); }
}
"#,
    )
    .unwrap();
    tool(
        temp.path(),
        "javac",
        &["--release", "8", "-d", "fixture", "Fixture.java"],
    );
    let original = fs::read(temp.path().join("fixture/Fixture.class")).unwrap();
    let mut strings = StringPool::new();
    let transformed = classfile::transform(&original, &mut strings, Limits::default())
        .unwrap()
        .unwrap();
    vector(&mut vectors, 1, true, &transformed, &original, &strings);
    count += 1;
    let mut invalid_version = transformed.clone();
    invalid_version[6..8].copy_from_slice(&0u16.to_be_bytes());
    assert!(classfile::restore(&invalid_version, &strings, Limits::default()).is_err());
    vector(
        &mut vectors,
        1,
        false,
        &invalid_version,
        &original,
        &strings,
    );
    count += 1;
    vector(
        &mut vectors,
        1,
        false,
        &transformed[..transformed.len() - 1],
        &original,
        &strings,
    );
    count += 1;
    vector(&mut vectors, 1, false, &transformed, &original, &pool);
    count += 1;
    vector(
        &mut vectors,
        1,
        false,
        &transformed,
        &original[..original.len() - 1],
        &strings,
    );
    count += 1;
    vectors[..4].copy_from_slice(&(count as u32).to_be_bytes());
    let data = temp.path().join("vectors.bin");
    fs::write(&data, vectors).unwrap();
    let path = std::env::join_paths([temp.path().join("classes"), jar]).unwrap();
    tool(
        temp.path(),
        "java",
        &[
            "-cp",
            path.to_str().unwrap(),
            "org.janex.reader.internal.codec.CodecTest",
            data.to_str().unwrap(),
        ],
    );
    if let Some(home) = std::env::var_os("JANEX_TEST_JAVA8_HOME") {
        let java =
            Path::new(&home)
                .join("bin")
                .join(if cfg!(windows) { "java.exe" } else { "java" });
        tool(
            temp.path(),
            java.to_str().unwrap(),
            &[
                "-cp",
                path.to_str().unwrap(),
                "org.janex.reader.internal.codec.CodecTest",
                data.to_str().unwrap(),
            ],
        );
    }
}
