# Copyright (c) 2026 Glavo
# SPDX-License-Identifier: MPL-2.0

[package]
name = "janex-format"
version.workspace = true
edition.workspace = true
description = "Janex container encoding, validation, and resource access"
license = "MPL-2.0"

[dependencies]
fluent-uri = "0.4"
half = "2"
language-tags = "0.3"
minicbor = { version = "2.3", features = ["std"] }
packageurl = "0.7"
sha2 = "0.11"
sm3 = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zstd.workspace = true

[lints]
workspace = true
