# Copyright (c) 2026 Glavo
# SPDX-License-Identifier: MPL-2.0

[package]
name = "janex-format"
version.workspace = true
edition.workspace = true
description = "Janex container encoding, validation, and resource access"
license = "MPL-2.0"

[dependencies]
cms = "0.2.3"
der = { version = "0.7", features = ["derive", "oid", "pem", "std"] }
fluent-uri = "0.4"
half = "2"
language-tags = "0.3"
minicbor = { version = "2.3", features = ["std"] }
packageurl = "0.7"
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
p384 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
pgp = { version = "0.20", default-features = false }
pkcs8 = { version = "0.10", features = ["encryption", "pem", "std"] }
rand = "0.8"
rsa = { version = "0.9", features = ["sha2"] }
sha2 = "0.11"
sha2-legacy = { package = "sha2", version = "0.10", features = ["oid"] }
signature = "2"
sm3 = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh64"] }
x509-cert = { version = "0.2", features = ["pem", "std"] }
zeroize = "1"
zstd = "0.14"

[lints]
workspace = true
